### PR TITLE
Update the French translation

### PR DESCRIPTION
**Pull request by AshtakaOOf**
~~Currently WIP.~~
I wanted you to have a way to track this. :)

### CODE REVIEW

**Comment by AshtakaOOf** [comment]
I'll squash the commits when it's ready for merging.

**Comment by AshtakaOOf** [comment]
This is almost done, I'll be doing some proofreading and then putting the PR into ready for review.

**Comment by AshtakaOOf** [comment]
This should be ready for review now. :D

**Comment by mcmonkey4eva** [comment]
_(Review is pretty much just making sure nothing weird is visibly in there, I definitely can't check the correctness lol)_

Thank you!

**Comment by mcmonkey4eva** [comment]
... Welp, lesson learned, next time there's a language PR I will have to add "run a JSON validator over it" first.

Please do test that things look correct in-UI btw, would've caught that particular error (by way of the UI failing to boot apparently) and could catch other slips.

**Comment by AshtakaOOf** [comment]
oops :3

**Pull request merged**
