### PR TITLE
update zh.json，校正并添加部分键值

### PR DESCRIPTION
**Pull request by xhoxye**
I used bingchat AI to revise it again and manually correct it, adding some uncommitted keys
QQ截图20240128230409
QQ截图20240128230450
QQ截图20240128230457

### CODE REVIEW

**Comment by xhoxye** [comment]
But there are some key values that are missing.
QQ截图20240128231614
QQ截图20240128231608
QQ截图20240128231621

**Comment by mcmonkey4eva** [comment]
Hi, so, I don't speak the language so so I'm just quickly using google translate to make sure it looks roughly valid (ie mainly just to verify this isn't a troll PR)

I noticed you may be preserving some AI-generated errors here, eg your updated
```
"Init Image Reset To Norm": "将初始图像重置为标准",
```
Says `Reset initial image to standard` according to google translate, while the original said `Reset to normal state`
Both of these translations are wrong: "Norm" here means the mathematical middle value, not a standard/normal state. If that's not easily translated, a word that means "Empty" would be closer.

A lot of other things are a little weird but in ways I assume that's just my lazy use of google translate to check things -- whereas the above sounds like the wrong concept was applied from lack of context.

So I'd encourage if you go through again to double-check the intended meaning of concepts, as a lot of keywords in here are highly technical and what the AI translation gave is probably contextually wrong.

That said though, this looks good, I appreciate the work to clean this up! Thank you!

---

re missing values - yeah, not everything is tracked ATM.

I added some of those: https://github.com/Stability-AI/StableSwarmUI/commit/5b37c417b4bbe0129124a06a9ab0e4de4267076b and in https://github.com/Stability-AI/StableSwarmUI/commit/9af6e5cf689143a82b4a2cbe402d8ceaf4c19219

You can see how I added them in those commits so feel free to add more yourself in the same way if you find more missing slots.

I updated the English reference file as well and will be rerunning the automated translations with it soon.

**Comment by mcmonkey4eva** [comment]
New keys from the early change are added: https://github.com/Stability-AI/StableSwarmUI/commit/5eeac85ef61af328d89da27c9a516678bf6fa98b

**Comment by xhoxye** [comment]
nice, I'm going to keep correcting.

**Pull request merged**
